# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from .listWidget import QCustomListWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 902)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(10, 0, 371, 51))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.aTicNameLineBox = QtWidgets.QLineEdit(self.horizontalFrame)
        self.aTicNameLineBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.aTicNameLineBox.setStyleSheet(
            "color: black;\n"
            "border: 1px solid rgb(166, 169, 169);\n"
            "border-radius: 3px;\n"
            "color: black;\n"
            ""
        )
        self.aTicNameLineBox.setObjectName("aTicNameLineBox")
        self.horizontalLayout.addWidget(self.aTicNameLineBox)
        self.aTicValSpinBox = QtWidgets.QDoubleSpinBox(self.horizontalFrame)
        self.aTicValSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.aTicValSpinBox.setStyleSheet("color:black;\n" "")
        self.aTicValSpinBox.setObjectName("aTicValSpinBox")
        self.aTicValSpinBox.setMaximum(10000.0)
        self.aTicValSpinBox.setMinimum(0)
        self.horizontalLayout.addWidget(self.aTicValSpinBox)
        self.aTicComboBox = QtWidgets.QComboBox(self.horizontalFrame)
        self.aTicComboBox.addItems(["UP", "DOWN"])
        self.aTicComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.aTicComboBox.setStyleSheet(
            "border: 1px solid rgb(166, 169, 169);\n"
            "border-radius: 3px;\n"
            "color: black;\n"
            ""
        )
        self.aTicComboBox.setObjectName("aTicComboBox")
        self.horizontalLayout.addWidget(self.aTicComboBox)
        self.aTicButton = QtWidgets.QToolButton(self.horizontalFrame)
        self.aTicButton.setStyleSheet("background-color: rgb(255, 255, 255)")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("src/gui/icons/bell.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.aTicButton.setIcon(icon)
        self.aTicButton.setObjectName("aTicButton")
        self.horizontalLayout.addWidget(self.aTicButton)
        self.aTicListWidget = QCustomListWidget(self.centralwidget)
        self.aTicListWidget.setGeometry(QtCore.QRect(10, 60, 661, 191))
        self.aTicListWidget.setStyleSheet("border: 1px solid rgb(166, 169, 169);")
        self.aTicListWidget.setObjectName("aTicListWidget")
        self.aTicListWidget.setStyleSheet(
            """
                item:selected {
                        background: rgb(255,255,255);
                }
                """
        )
        self.nTicListWidget = QCustomListWidget(self.centralwidget)
        self.nTicListWidget.setGeometry(QtCore.QRect(680, 60, 711, 751))
        self.nTicListWidget.setStyleSheet("border: 1px solid rgb(166, 169, 169);")
        self.nTicListWidget.setObjectName("nTicListWidget")
        self.newsListWidget = QCustomListWidget(self.centralwidget)
        self.newsListWidget.setGeometry(QtCore.QRect(10, 260, 661, 551))
        self.newsListWidget.setStyleSheet("border: 1px solid rgb(166, 169, 169);")
        self.newsListWidget.setObjectName("newsListWidget")
        self.nTicNameComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.nTicNameComboBox.setGeometry(QtCore.QRect(680, 15, 100, 20))
        self.nTicNameComboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nTicNameComboBox.setStyleSheet(
            "border: 1px solid rgb(166, 169, 169);\n"
            "border-radius: 3px;\n"
            "color: black;\n"
            ""
        )
        self.nTicNameComboBox.setObjectName("nTicNameComboBox")
        self.ticPriceLCDNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.ticPriceLCDNumber.setGeometry(QtCore.QRect(800, 12, 64, 23))
        self.ticPriceLCDNumber.setStyleSheet("border: None")
        self.ticPriceLCDNumber.setObjectName("ticPriceLCDNumber")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.aTicButton.setText(_translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
